# Generated by Django 5.2.11 on 2026-03-01 13:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_flat_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='normalize_owners_phonenumber',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Нормализованный номер владельца'),
        ),
    ]
