# Generated by Django 5.2.11 on 2026-03-01 15:15

from django.db import migrations
import phonenumbers


def numbers_normalisation(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phonenumber_specification = phonenumbers.parse(
            flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phonenumber_specification):
            normalized_phonenumber = phonenumbers.format_number(
                phonenumber_specification,
                phonenumbers.PhoneNumberFormat.E164)
            flat.owner_pure_phone = normalized_phonenumber
            flat.save()
        else:
            flat.owner_pure_phone = None
            flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = None
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(numbers_normalisation, move_backward)
    ]