# Generated by Django 5.2.11 on 2026-03-02 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_flats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owners_phonenumber',
            new_name='owner_phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='owner_phonenumber',
        ),
    ]
