# Generated by Django 5.2.11 on 2026-03-02 17:16

from django.db import migrations


def transfer_owners_data(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            owner=flat.owner,
            owner_phonenumber=flat.owner_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_owners_phonenumber_flat_owner_phonenumber_and_more'),
    ]

    operations = [
        migrations.RunPython(transfer_owners_data)
    ]
