# Generated by Django 5.2.11 on 2026-03-02 18:12

from django.db import migrations


def link_owner_and_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get_or_create(
            owner=flat.owner,
            owner_phonenumber=flat.owner_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )[0]
        owner.flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_auto_20260302_2016'),
    ]

    operations = [
        migrations.RunPython(link_owner_and_flat)
    ]
