# Generated by Django 5.2.11 on 2026-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_remove_flat_owner_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='owner_full_name',
        ),
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flats_in_possession', to='property.flat', verbose_name='Квартиры во владении'),
        ),
    ]
