# Generated by Django 5.2.11 on 2026-03-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_rename_owner_owner_owner_full_name_alter_owner_flats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Собственник', 'verbose_name_plural': 'Собственники'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
    ]
